### PR TITLE
initial code commit

### PR DESCRIPTION
**Pull request by schan2023**

### CODE REVIEW

**Comment by schan2023** [comment]
[Add driver-common microservice](https://trello.com/c/zKRD9QNf/80-add-driver-common-microservice)

**Comment by R4il** [comment]
.gitignore missing

**Review by R4il — APPROVED** [review]

**Comment by Castyr** [comment]
Add .gradle and .idea to .gitignore

**Review by R4il — APPROVED** [review]

**Review by R4il — APPROVED** [review]

**Review by R4il — APPROVED** [review]
ok

**Pull request merged**
